// Array på værkerne

const art = [
    {
        id: 1,
        year: 1853-1936,
        title: "En erindring efter Danmarks største martyr",
        artist: "Frits Albert Florintinus Strand",
        material: "Olie på lærred",
        size: "56x49 cm",
        Image: "img/frits-albert-florintinus-strand.png",
        portrait: "Hans billeder var enkle og højtidelige og viser optrin, hvor han ofte selv er omdrejningspunkt. I hans billeder er fortællingen vigtigere end den teknisk korrekte fremstilling. Motiverne er glade og spontane.",
        about: "Han var optaget af døden, særligt sin egen, og ville begraves i en lang diplomatfrakke.",
        psychiatry: "Frits Alberts Florentinus Strand var indlagt på psykiatrisk hospital i 29 år (1907-1936). Alkohol var en af årsagerne til han ikke kunne være hjemme hos sin kone.",
    },
    {
        id: 2,
        year: 1946-,
        title: "ingen titel",
        artist: "Jette Hansen",
        material: "Olie på lærred",
        Image: "img/jette-hansen.png",
        portrait: "Typisk for Jette Hansen er en manglende respekt for værkets kant. Genstande og figurer bliver brat afskåret af billedrammen, som om historierne fylder langt mere, end der er plads til. Værkernes univers er flydende og figurerne forholder sig ikke til lodret og vandret.",
        psychiatry: "Jette Hansen blev syg i 1968, og indlagt på Psykiatrisk Hospital i Risskov, hvor hun var i 4 år. I 1989 begyndte hun på Gallo-skolen til tegning og maleri. Dette blev et vendepunkt i hendes liv, og hun blev psykisk mere stabil.",
    },
    {
        id: 3,
        year: 1942-2008,
        title: "ingen titel",
        artist: "Marie Heiberg",
        material: "Olie på lærred",
        Image: "img/marie-heiberg.png",
        portrait: "En del af maleriernes figurer er kendetegnet ved klovneagtige træk. Figurerne optræder i forskellige sammenhænge ofte i et spændingsfelt mellem tristhed og håb. Hendes værker er dramatiske, men også følsomme. De udtrykker en sart tristhed en gennemgående melankoli, der forstærkes af hendes blå univers.",
        about: "Hun var en dygtig maler, uddannet violinist og sanger i et kor.",
        psychiatry: "Marie Heiberg har malet en del malerier først i 1970’erne i forbindelse med psykisk sygdom og indlæggelse.",
    },
    {
        id: 4,
        year: 1951-2012,
        title: "Portræt",
        artist: "Ole Norge",
        material: "Oliekridt",
        size: "31x44 cm",
        Image: "img/ole-norge.png",
        portrait: "En ung mand med gylden hårpragt og sortrandende øjne ser lige igennem os - Øjnene er skræmte",
        about: "Ole Norges værker er farverige, men udtrykker også en skrøbelighed. Værkerne opløses i farvefelter eller mekaniske linjer og former.",
        psychiatry: "Ole Norge var i kontakt med psykiatrien, efter at han i en ung alder havde en psykotisk episode, hvor han identificerede sig med Jesus. Han oplevede det som forløsende at male og tegne.",
    },
    {
        id: 5,
        year: 1951-1986,
        title: "Luder og Madonna",
        artist: "Patrick Larsen",
        material: "Acryl og oliekridt",
        size: "54x50 cm",
        Image: "img/patrick-larsen.png",
        portrait: "Patrick Larsen portrætter samfundets bagside, og skildrer magtesløshed og nederlag. Hans maleteknik med farver i flere lag er mættet, og det giver billederne følelsesmæssig intensitet. Gul er en gennemgående farve -mellem smerte og ulykke.",
        about: "Patrick Larsen havde et hårdt liv og en alt for tidlig dø. I hans værker bevæger han sig tit omkring temaerne død, angst og lidelse",
        psychiatry: "Hårde miljøer var rammen om hans eget liv og alt for tidlige død. De mørke følelser har ligget i Patrick Larsens eget sind og har koblet med en stor følsomhed har det medført hårde sammenstød med tilværelsen.",
    }
]